services:
  mongodb:
    image: mongo:latest
    container_name: habittrack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongodb-test:
    image: mongo:latest
    container_name: habittrack-mongo-test
    ports:
      - "27018:27017"
    volumes:
      - mongo-test-data:/data/db

volumes:
  mongo-data:
  mongo-test-data:
